spring.application.name=login-auth-api

## Banco de dados
spring.datasource.url=jdbc:h2:mem:loginapi
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

## Security
api.security.token.secret=
